// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"book_manager/internal/handler"
	"book_manager/internal/repository"
	"book_manager/internal/server"
	"book_manager/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func newApp() (*gin.Engine, func(), error) {
	db := repository.GetDB()
	bookRepository := repository.NewBookRepository(db)
	bookService := service.NewBookService(bookRepository)
	bookHandler := handler.NewBookHandler(bookService)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	borrowRepository := repository.NewBorrowRepository(db)
	borrowService := service.NewBorrowService(borrowRepository, bookRepository)
	borrowHandler := handler.NewBorrowHandler(borrowService)
	engine := server.NewRouter(bookHandler, userHandler, borrowHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewBookRepository, repository.NewUserRepository, repository.NewBorrowRepository)

var ServiceSet = wire.NewSet(service.NewBookService, service.NewUserService, service.NewBorrowService)

var HandlerSet = wire.NewSet(handler.NewBookHandler, handler.NewUserHandler, handler.NewBorrowHandler)

var ServerSet = wire.NewSet(server.NewRouter)

var ConfigSet = wire.NewSet(repository.GetDB)
